import { AnalysisResult } from '../types';
import { getProvider, ProviderId } from '../lib/providers';
import { cn } from '../lib/utils';
import { Shield, CheckCircle2, AlertTriangle, XCircle, Link as LinkIcon } from 'lucide-react';

interface ReportPrintViewProps {
  prompt: string;
  compareResults: {
    provider: ProviderId;
    output: string;
    result?: AnalysisResult;
    error?: string;
  }[];
}

export default function ReportPrintView({ prompt, compareResults }: ReportPrintViewProps) {
  // Filter out models that failed
  const validResults = compareResults.filter(r => r.result !== undefined);
  if (validResults.length === 0) return null;

  // Calculate the "winner" (most reliable) based on factuality + inverse bias + safety + consistency
  const getScore = (res: AnalysisResult) => {
    return res.overallScores.factuality + (100 - res.overallScores.bias) + res.overallScores.safety + res.overallScores.consistency;
  };

  const sortedResults = [...validResults].sort((a, b) => getScore(b.result!) - getScore(a.result!));
  const winner = sortedResults[0];

  return (
    <div className="hidden print:block print:bg-white print:text-black min-h-screen p-8 text-sm font-sans max-w-4xl mx-auto">
      
      {/* Header */}
      <div className="border-b-2 border-black pb-4 mb-6 flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold uppercase tracking-widest text-black">Multi-LLM Integrity Report</h1>
          <p className="text-gray-500 font-mono text-xs mt-1">Generated by Halci AI TrustLens™</p>
        </div>
        <div className="flex items-center gap-2">
          <Shield className="w-8 h-8 text-black" />
          <span className="font-bold text-xl">HALCI</span>
        </div>
      </div>

      {/* 1. User Query */}
      <div className="mb-8 bg-gray-50 p-4 rounded-lg border border-gray-200">
        <h2 className="text-xs font-bold font-mono text-gray-500 uppercase mb-2">User Query</h2>
        <p className="text-base text-gray-900">{prompt}</p>
      </div>

      {/* 2. Comparison Summary Table */}
      <div className="mb-8">
        <h2 className="text-lg font-bold border-b border-gray-300 pb-2 mb-4">Comparison Summary</h2>
        <table className="w-full text-left border-collapse">
          <thead>
            <tr className="bg-gray-100 font-bold text-xs uppercase tracking-wider text-gray-600">
              <th className="p-3 border-b border-gray-300">Model</th>
              <th className="p-3 border-b border-gray-300">Hallucination Risk</th>
              <th className="p-3 border-b border-gray-300">Bias Score</th>
              <th className="p-3 border-b border-gray-300">Consistency</th>
              <th className="p-3 border-b border-gray-300">Verdict</th>
            </tr>
          </thead>
          <tbody>
            {validResults.map((cr) => {
              const res = cr.result!;
              const provider = getProvider(cr.provider);
              const isWinner = cr.provider === winner.provider;
              const hallucinationRisk = 100 - res.overallScores.factuality;
              
              let biasLabel = "Low";
              if (res.overallScores.bias > 60) biasLabel = "High";
              else if (res.overallScores.bias > 30) biasLabel = "Medium";

              return (
                <tr key={cr.provider} className={cn("border-b border-gray-200", isWinner ? "bg-green-50/50" : "")}>
                  <td className="p-3 font-bold text-gray-900 flex items-center gap-2">
                    {provider.name} {isWinner && <span className="px-2 py-0.5 bg-green-200 text-green-800 text-[10px] rounded-full uppercase ml-2">Best Performer</span>}
                  </td>
                  <td className="p-3">
                    <span className={cn(hallucinationRisk > 50 ? "text-red-600 font-bold" : hallucinationRisk > 20 ? "text-yellow-600" : "text-green-600")}>
                      {hallucinationRisk}%
                    </span>
                  </td>
                  <td className="p-3">
                    <span className={cn(res.overallScores.bias > 60 ? "text-red-600 font-bold" : res.overallScores.bias > 30 ? "text-yellow-600" : "text-green-600")}>
                      {biasLabel} ({res.overallScores.bias}%)
                    </span>
                  </td>
                  <td className="p-3">{res.overallScores.consistency}%</td>
                  <td className="p-3 font-mono text-xs">{res.overallVerdict}</td>
                </tr>
              );
            })}
          </tbody>
        </table>
      </div>

      {/* 3 & 4. Claim-Level Verification & Sources */}
      <div className="mb-8" style={{ pageBreakBefore: 'always' }}>
        <h2 className="text-lg font-bold border-b border-gray-300 pb-2 mb-6">Claim-Level Verification</h2>
        
        {validResults.map((cr) => {
          const provider = getProvider(cr.provider);
          return (
            <div key={cr.provider} className="mb-10">
              <h3 className="font-bold text-base mb-3 bg-gray-100 p-2 rounded inline-block">
                Model: {provider.name}
              </h3>
              
              <div className="space-y-4">
                {cr.result!.sentenceAudits.map((audit, idx) => {
                  let statusIcon = <CheckCircle2 className="w-4 h-4 text-green-600" />;
                  let statusText = "Verified";
                  let statusColor = "bg-green-50 border-green-200";
                  
                  if (audit.status === 'error') {
                    statusIcon = <XCircle className="w-4 h-4 text-red-600" />;
                    statusText = "Unsupported";
                    statusColor = "bg-red-50 border-red-200";
                  } else if (audit.status === 'warning') {
                    statusIcon = <AlertTriangle className="w-4 h-4 text-yellow-600" />;
                    statusText = "Partial / Caution";
                    statusColor = "bg-yellow-50 border-yellow-200";
                  }

                  return (
                    <div key={idx} className={cn("border rounded-lg p-4", statusColor)} style={{ pageBreakInside: 'avoid' }}>
                      <div className="flex items-start gap-3">
                        <div className="mt-0.5 flex-shrink-0 flex flex-col items-center">
                          {statusIcon}
                          <span className="text-[9px] font-bold uppercase mt-1 text-gray-600">{statusText}</span>
                        </div>
                        <div className="flex-1">
                          <p className="text-gray-900 font-medium mb-3">"{audit.text}"</p>
                          
                          <div className="grid grid-cols-3 gap-4 mb-3 text-xs bg-white/60 p-2 rounded border border-black/5">
                            <div>
                              <span className="font-mono text-gray-500 block text-[9px] uppercase">Hallucination Check</span>
                              <span className={audit.checks.hallucination.status === 'pass' ? "text-green-700" : "text-red-700"}>{audit.checks.hallucination.explanation}</span>
                            </div>
                            <div>
                              <span className="font-mono text-gray-500 block text-[9px] uppercase">Bias Check</span>
                              <span className={audit.checks.bias.status === 'pass' ? "text-green-700" : "text-red-700"}>{audit.checks.bias.explanation}</span>
                            </div>
                            <div>
                              <span className="font-mono text-gray-500 block text-[9px] uppercase">Consistency Check</span>
                              <span className={audit.checks.consistency.status === 'pass' ? "text-green-700" : "text-red-700"}>{audit.checks.consistency.explanation}</span>
                            </div>
                          </div>

                          {/* Sources */}
                          {audit.sources && audit.sources.length > 0 && (
                            <div className="mt-2 text-xs border-t border-black/10 pt-2">
                              <span className="font-bold flex items-center gap-1 text-gray-700 mb-1">
                                <LinkIcon className="w-3 h-3" /> Evidence / Sources
                              </span>
                              <ul className="list-disc pl-5 space-y-0.5">
                                {audit.sources.map((src, i) => (
                                  <li key={i}>
                                    <a href={src.link} className="text-blue-600 underline" target="_blank" rel="noreferrer">
                                      {src.title}
                                    </a>
                                  </li>
                                ))}
                              </ul>
                            </div>
                          )}
                        </div>
                      </div>
                    </div>
                  );
                })}
              </div>
            </div>
          );
        })}
      </div>

      {/* 5. Final Verdict */}
      <div className="mt-12 bg-gray-900 text-white p-6 rounded-xl" style={{ pageBreakInside: 'avoid' }}>
        <h2 className="text-lg font-bold mb-4 flex items-center gap-2">
          <Shield className="w-5 h-5 text-indigo-400" /> Final Verdict
        </h2>
        <div className="space-y-2">
          <p className="text-sm text-gray-300">
            Based on the rigorous Halci AI integrity evaluation across multiple LLMs, the most reliable model for this query is:
          </p>
          <p className="text-xl font-bold text-indigo-400">
            {getProvider(winner.provider).name}
          </p>
          <p className="text-sm text-gray-400 mt-2">
            This model achieved the highest composite score (Factuality: {winner.result!.overallScores.factuality}%, Bias: {winner.result!.overallScores.bias}%, Consistency: {winner.result!.overallScores.consistency}%), demonstrating superior grounding and neutrality compared to the alternatives.
          </p>
        </div>
      </div>

    </div>
  );
}
